# Generated by Django 5.2 on 2025-08-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="saved_jobs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Jobs this user has saved",
                related_name="saved_by_users",
                to="jobs.job",
            ),
        ),
    ]
