# Generated by Django 5.2 on 2025-07-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("company_logo", models.URLField(blank=True, null=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Internship", "Internship"),
                            ("Full-time", "Full-time"),
                        ],
                        default="Internship",
                        max_length=50,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("stipend_or_pay", models.CharField(blank=True, max_length=100)),
                ("duration", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("platform_posted_on", models.CharField(max_length=100)),
                ("posted_at", models.DateField()),
                ("deadline", models.DateField(blank=True, null=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("link", models.URLField()),
                ("description", models.TextField(blank=True, null=True)),
                ("skills", models.TextField(blank=True, null=True)),
                ("signature", models.CharField(default="", max_length=64, unique=True)),
            ],
        ),
    ]
